spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      name: environment
management:
  endpoints:
    web:
      exposure:
        include: "*"