spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      name: environment
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234
management:
  endpoints:
    web:
      exposure:
        include: "*"