// ./gradlew bootRun --args='--spring.profiles.active={profile}'

GET localhost:{{port}}/environment

### 어플리키이션을 종료시키지 않고 설정 정보 하나 refresh
POST localhost:{{port}}/actuator/refresh

### 어플리키이션을 종료시키지 않고 연결되어 있는 설정정보 전체 변경 refresh
POST localhost:{{port}}/actuator/busrefresh