GET http://localhost:8888/environment/{{profile}}

###
POST http://localhost:8888/encrypt
Content-Type: application/json

"{{passowrd}}"


###
POST http://localhost:8888/decrypt
Content-Type: application/json

"{chiper}1a9d3fee6b2780839bd1dc7d1c332daf0576dd08b057defad271e9ecd163f1a3"